# Generated by Django 5.1.4 on 2024-12-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='smobile',
            field=models.CharField(max_length=10, verbose_name='Mobile: '),
        ),
    ]
